### ISSUE TITLE
Not showing shortcuts in Picker

### ISSUE THREAD

**Issue by cmacfadyen** [isaackrementsov/cvu-portfolio-app#13]
I'm noticing that shortcuts show up as items in the Google Picker, so you see both the original file and the shortcut. Can you filter out shortcuts from the picker?
<img width="500" alt="Screen Shot 2021-06-24 at 5 41 48 PM" src="https://user-images.githubusercontent.com/10223598/123336346-bef8bf80-d513-11eb-9321-b1db8a118c6a.png">

**Comment by isaackrementsov** [comment]
I tried using the `View.setMimeTypes` option in the Picker API to prevent this (using every mime type except `application/vnd.google-apps.shortcut`), but it doesn't seem to hide anything, probably because the shortcuts are to allowed mime types. 

However, selecting a shortcut in Picker just points to the original file, so this doesn't seem to cause any issues. For that reason, I'm going to close this issue, but feel free to re-open it if you notice further problems.
